### ISSUE TITLE
Add more settings to the installers

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#2525]
## Description
as the title explains it should be useful to allow administrators to define the app timezone and language when using the installer. 

## Todo
- [x] Add a selectbox with all php timezones to define the default timezone.
- [x] Add a selectbox with all available languages to define the default language.
- [x] Add a selectbox with all available currencies to define the default currency.
- [X] Add the above options to the **bagisto:install** command.
- [x] Split application and database settings in different divs/views to prevent long forms.

**Comment by jitendra-webkul** [comment]
Implemented in #2551 PR
