### ISSUE TITLE
Allow the admin to set the frontend in maintenance mode

### ISSUE THREAD

**Issue by ghermans** [bagisto/bagisto#4242]
## Todo

- [x] Add a option for each channel to enable / disable the maintenance mode.
- [x] Add a textfield to define the maintenance text that is displayed on the frontend.
- [x] Add a option to set IP addresses who can access the frontend during maintenance mode.

**Comment by richmondnursery** [comment]
Laravel 8 has a similar feature set included in the framework now. May be worth simply working on migrating to Laravel 8 instead of re-inventing the wheel so to speak.

**Comment by ghermans** [comment]
I know Laravel 8 includes this feature, and the migration is also planned.
Nevertheless, the admin should be able to set this via the admin interface as this is more user-friendly
